### ISSUE TITLE
Not fetching data from Google Analytics

### ISSUE THREAD

**Issue by Nandhini-Kumaresan** [datainsider-co/rocket-bi#98]
Hi,
Data from google analytics account is not fetching. Below screenshot shows the status of the created job.

![image](https://github.com/datainsider-co/rocket-bi/assets/148965262/9d6445bb-7200-4213-9b23-02b5c2b3fdca)

**Comment by tvc12** [comment]
Hi @Nandhini-Kumaresan ,
Can you show me a message error in **Jobs History** ?

**Comment by Nandhini-Kumaresan** [comment]
Hi @tvc12 ,
Below is the error message in **Jobs History**.

`Start sync job Ga4Job(orgId: 0, syncId: 14, jobId: 6) Error when sync job, cause init reader failed, cause io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. delete temporary table __di_tmp_event_1701230876615 successfully`

**Comment by tvc12** [comment]
Hi @Nandhini-Kumaresan,
The bug is fixed in the next release. We are planning an update for the day after tomorrow, which is 2023-11-30. 

For workaround, you edit google analytics source > click re-connection again > update source > force run job.

![image](https://github.com/datainsider-co/rocket-bi/assets/35712888/4309982c-6b84-46eb-80e6-6fe8a2c389f3)

**Comment by tvc12** [comment]
hi @Nandhini-Kumaresan,
Checkout the release in [here](https://github.com/datainsider-co/rocket-bi/releases/tag/v23.11.30)  and update new [docker-compose.yml](https://github.com/datainsider-co/rocket-bi/blob/main/docker/docker-compose.yml).
